
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TESIS = 28;
  public static final int REAL2INT = 15;
  public static final int TIPO = 33;
  public static final int POR = 26;
  public static final int VARS = 16;
  public static final int CLOG = 37;
  public static final int CENT = 34;
  public static final int EXPONENCIAL = 19;
  public static final int PC = 20;
  public static final int INT2REAL = 14;
  public static final int NOT = 9;
  public static final int AND = 10;
  public static final int IGUALQUE = 29;
  public static final int MAYORQUE = 23;
  public static final int CREAL = 35;
  public static final int OR = 11;
  public static final int PLOT = 7;
  public static final int DIV = 25;
  public static final int IF = 2;
  public static final int UMENOS = 32;
  public static final int ASOP = 21;
  public static final int EOF = 0;
  public static final int SIZE = 12;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MENOS = 31;
  public static final int IDENT = 38;
  public static final int COLOR = 36;
  public static final int MENORQUE = 22;
  public static final int ELSE = 4;
  public static final int COSENO = 18;
  public static final int WHILE = 6;
  public static final int SENO = 17;
  public static final int THEN = 3;
  public static final int PROG = 13;
  public static final int END = 5;
  public static final int PAREN = 27;
  public static final int DO = 8;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "WHILE",
  "PLOT",
  "DO",
  "NOT",
  "AND",
  "OR",
  "SIZE",
  "PROG",
  "INT2REAL",
  "REAL2INT",
  "VARS",
  "SENO",
  "COSENO",
  "EXPONENCIAL",
  "PC",
  "ASOP",
  "MENORQUE",
  "MAYORQUE",
  "MAS",
  "DIV",
  "POR",
  "PAREN",
  "TESIS",
  "IGUALQUE",
  "COMA",
  "MENOS",
  "UMENOS",
  "TIPO",
  "CENT",
  "CREAL",
  "COLOR",
  "CLOG",
  "IDENT"
  };
}

